name: lobby
version: '1.0-SNAPSHOT'
main: sh.harold.fulcrum.lobby.LobbyPlugin
bootstrapper: sh.harold.fulcrum.lobby.bootstrap.LobbyBootstrapper
api-version: '1.21'
dependencies:
  bootstrap:
    Fulcrum:
      load: BEFORE
      required: true
  server:
    Fulcrum:
      load: BEFORE
      required: true
